import type { Skill } from './types'
import { SkillStatus } from './types'

/**
 * 模拟技能数据
 */
export const mockSkills: Skill[] = [
  {
    id: 'skill_001',
    name: 'PostgreSQL 故障诊断',
    description: '自动分析 PostgreSQL 数据库的性能问题，包括慢查询、锁等待、连接池状态等，提供优化建议和解决方案。',
    icon: '🐘',
    status: SkillStatus.ONLINE,
    creator: '张三',
    createdAt: '2024-07-02',
    sessionId: 'session_xyz123',
    tags: ['postgres', '故障分析', '锁分析'],
  },
  {
    id: 'skill_002',
    name: 'Redis 缓存优化',
    description: '监控 Redis 缓存命中率，分析热点数据，提供缓存策略优化建议，支持缓存穿透和雪崩问题诊断。',
    icon: '🔴',
    status: SkillStatus.ONLINE,
    creator: '李四',
    createdAt: '2024-06-28',
    sessionId: 'session_abc456',
    tags: ['redis', '缓存', '性能优化'],
  },
  {
    id: 'skill_003',
    name: 'Kubernetes 集群监控',
    description: '实时监控 K8s 集群状态，包括 Pod 健康检查、资源使用情况、节点状态等，自动发现异常并告警。',
    icon: '☸️',
    status: SkillStatus.DISABLED,
    creator: '王五',
    createdAt: '2024-06-15',
    sessionId: 'session_def789',
    tags: ['kubernetes', '监控', '运维'],
  },
  {
    id: 'skill_004',
    name: 'API 性能分析',
    description: '分析 RESTful API 的响应时间、错误率、吞吐量等指标，识别性能瓶颈，提供优化方案。',
    icon: '🚀',
    status: SkillStatus.ONLINE,
    creator: '赵六',
    createdAt: '2024-07-01',
    sessionId: 'session_ghi012',
    tags: ['api', '性能', '监控'],
  },
  {
    id: 'skill_005',
    name: 'MySQL 慢查询优化',
    description: '自动捕获和分析 MySQL 慢查询日志，提供索引优化建议，帮助提升数据库查询性能。',
    icon: '🐬',
    status: SkillStatus.ONLINE,
    creator: '孙七',
    createdAt: '2024-06-20',
    sessionId: 'session_jkl345',
    tags: ['mysql', '慢查询', '索引优化'],
  },
  {
    id: 'skill_006',
    name: 'Nginx 日志分析',
    description: '解析 Nginx 访问日志和错误日志，统计流量趋势、状态码分布、热门 URL 等，支持异常流量检测。',
    icon: '🟢',
    status: SkillStatus.DISABLED,
    creator: '周八',
    createdAt: '2024-06-10',
    sessionId: 'session_mno678',
    tags: ['nginx', '日志分析', '流量监控'],
  },
  {
    id: 'skill_007',
    name: 'Docker 容器健康检查',
    description: '监控 Docker 容器的运行状态、资源占用、日志输出等，自动重启异常容器，保障服务稳定性。',
    icon: '🐳',
    status: SkillStatus.ONLINE,
    creator: '吴九',
    createdAt: '2024-07-05',
    sessionId: 'session_pqr901',
    tags: ['docker', '容器', '健康检查'],
  },
  {
    id: 'skill_008',
    name: 'ElasticSearch 查询优化',
    description: '分析 ES 查询性能，优化查询 DSL，提供分片和副本配置建议，提升搜索响应速度。',
    icon: '🔍',
    status: SkillStatus.ONLINE,
    creator: '郑十',
    createdAt: '2024-06-25',
    sessionId: 'session_stu234',
    tags: ['elasticsearch', '搜索', '性能优化'],
  },
]
