/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSkillsIndexRouteImport } from './routes/_authenticated/skills/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServiceManagementIndexRouteImport } from './routes/_authenticated/service-management/index'
import { Route as AuthenticatedObservabilityIndexRouteImport } from './routes/_authenticated/observability/index'
import { Route as AuthenticatedMcpManagementIndexRouteImport } from './routes/_authenticated/mcp-management/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedExternalCallsIndexRouteImport } from './routes/_authenticated/external-calls/index'
import { Route as AuthenticatedClusterChatIndexRouteImport } from './routes/_authenticated/cluster-chat/index'
import { Route as AuthenticatedAlertManagementIndexRouteImport } from './routes/_authenticated/alert-management/index'
import { Route as AuthenticatedAiChatIndexRouteImport } from './routes/_authenticated/ai-chat/index'
import { Route as AuthenticatedAgentManagementIndexRouteImport } from './routes/_authenticated/agent-management/index'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDebugAuthRouteImport } from './routes/_authenticated/debug/auth'
import { Route as AuthenticatedSettingsRolesIndexRouteImport } from './routes/_authenticated/settings/roles/index'
import { Route as AuthenticatedSettingsPermissionsIndexRouteImport } from './routes/_authenticated/settings/permissions/index'
import { Route as AuthenticatedSettingsMenusIndexRouteImport } from './routes/_authenticated/settings/menus/index'
import { Route as AuthenticatedLogsOperationIndexRouteImport } from './routes/_authenticated/logs/operation/index'
import { Route as AuthenticatedLogsChatIndexRouteImport } from './routes/_authenticated/logs/chat/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedServiceManagementIndexRoute =
  AuthenticatedServiceManagementIndexRouteImport.update({
    id: '/service-management/',
    path: '/service-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObservabilityIndexRoute =
  AuthenticatedObservabilityIndexRouteImport.update({
    id: '/observability/',
    path: '/observability/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMcpManagementIndexRoute =
  AuthenticatedMcpManagementIndexRouteImport.update({
    id: '/mcp-management/',
    path: '/mcp-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExternalCallsIndexRoute =
  AuthenticatedExternalCallsIndexRouteImport.update({
    id: '/external-calls/',
    path: '/external-calls/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClusterChatIndexRoute =
  AuthenticatedClusterChatIndexRouteImport.update({
    id: '/cluster-chat/',
    path: '/cluster-chat/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertManagementIndexRoute =
  AuthenticatedAlertManagementIndexRouteImport.update({
    id: '/alert-management/',
    path: '/alert-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiChatIndexRoute =
  AuthenticatedAiChatIndexRouteImport.update({
    id: '/ai-chat/',
    path: '/ai-chat/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentManagementIndexRoute =
  AuthenticatedAgentManagementIndexRouteImport.update({
    id: '/agent-management/',
    path: '/agent-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugAuthRoute = AuthenticatedDebugAuthRouteImport.update({
  id: '/debug/auth',
  path: '/debug/auth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRolesIndexRoute =
  AuthenticatedSettingsRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPermissionsIndexRoute =
  AuthenticatedSettingsPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMenusIndexRoute =
  AuthenticatedSettingsMenusIndexRouteImport.update({
    id: '/menus/',
    path: '/menus/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedLogsOperationIndexRoute =
  AuthenticatedLogsOperationIndexRouteImport.update({
    id: '/logs/operation/',
    path: '/logs/operation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsChatIndexRoute =
  AuthenticatedLogsChatIndexRouteImport.update({
    id: '/logs/chat/',
    path: '/logs/chat/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/debug/auth': typeof AuthenticatedDebugAuthRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/agent-management': typeof AuthenticatedAgentManagementIndexRoute
  '/ai-chat': typeof AuthenticatedAiChatIndexRoute
  '/alert-management': typeof AuthenticatedAlertManagementIndexRoute
  '/cluster-chat': typeof AuthenticatedClusterChatIndexRoute
  '/external-calls': typeof AuthenticatedExternalCallsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/mcp-management': typeof AuthenticatedMcpManagementIndexRoute
  '/observability': typeof AuthenticatedObservabilityIndexRoute
  '/service-management': typeof AuthenticatedServiceManagementIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/logs/chat': typeof AuthenticatedLogsChatIndexRoute
  '/logs/operation': typeof AuthenticatedLogsOperationIndexRoute
  '/settings/menus': typeof AuthenticatedSettingsMenusIndexRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsIndexRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/debug/auth': typeof AuthenticatedDebugAuthRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/agent-management': typeof AuthenticatedAgentManagementIndexRoute
  '/ai-chat': typeof AuthenticatedAiChatIndexRoute
  '/alert-management': typeof AuthenticatedAlertManagementIndexRoute
  '/cluster-chat': typeof AuthenticatedClusterChatIndexRoute
  '/external-calls': typeof AuthenticatedExternalCallsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/mcp-management': typeof AuthenticatedMcpManagementIndexRoute
  '/observability': typeof AuthenticatedObservabilityIndexRoute
  '/service-management': typeof AuthenticatedServiceManagementIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/logs/chat': typeof AuthenticatedLogsChatIndexRoute
  '/logs/operation': typeof AuthenticatedLogsOperationIndexRoute
  '/settings/menus': typeof AuthenticatedSettingsMenusIndexRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsIndexRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/debug/auth': typeof AuthenticatedDebugAuthRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/agent-management/': typeof AuthenticatedAgentManagementIndexRoute
  '/_authenticated/ai-chat/': typeof AuthenticatedAiChatIndexRoute
  '/_authenticated/alert-management/': typeof AuthenticatedAlertManagementIndexRoute
  '/_authenticated/cluster-chat/': typeof AuthenticatedClusterChatIndexRoute
  '/_authenticated/external-calls/': typeof AuthenticatedExternalCallsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/mcp-management/': typeof AuthenticatedMcpManagementIndexRoute
  '/_authenticated/observability/': typeof AuthenticatedObservabilityIndexRoute
  '/_authenticated/service-management/': typeof AuthenticatedServiceManagementIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/skills/': typeof AuthenticatedSkillsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/logs/chat/': typeof AuthenticatedLogsChatIndexRoute
  '/_authenticated/logs/operation/': typeof AuthenticatedLogsOperationIndexRoute
  '/_authenticated/settings/menus/': typeof AuthenticatedSettingsMenusIndexRoute
  '/_authenticated/settings/permissions/': typeof AuthenticatedSettingsPermissionsIndexRoute
  '/_authenticated/settings/roles/': typeof AuthenticatedSettingsRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/debug/auth'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/agent-management'
    | '/ai-chat'
    | '/alert-management'
    | '/cluster-chat'
    | '/external-calls'
    | '/help-center'
    | '/mcp-management'
    | '/observability'
    | '/service-management'
    | '/settings/'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/logs/chat'
    | '/logs/operation'
    | '/settings/menus'
    | '/settings/permissions'
    | '/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/debug/auth'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/agent-management'
    | '/ai-chat'
    | '/alert-management'
    | '/cluster-chat'
    | '/external-calls'
    | '/help-center'
    | '/mcp-management'
    | '/observability'
    | '/service-management'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/users'
    | '/logs/chat'
    | '/logs/operation'
    | '/settings/menus'
    | '/settings/permissions'
    | '/settings/roles'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/debug/auth'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/agent-management/'
    | '/_authenticated/ai-chat/'
    | '/_authenticated/alert-management/'
    | '/_authenticated/cluster-chat/'
    | '/_authenticated/external-calls/'
    | '/_authenticated/help-center/'
    | '/_authenticated/mcp-management/'
    | '/_authenticated/observability/'
    | '/_authenticated/service-management/'
    | '/_authenticated/settings/'
    | '/_authenticated/skills/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/logs/chat/'
    | '/_authenticated/logs/operation/'
    | '/_authenticated/settings/menus/'
    | '/_authenticated/settings/permissions/'
    | '/_authenticated/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/': {
      id: '/_authenticated/skills/'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/service-management/': {
      id: '/_authenticated/service-management/'
      path: '/service-management'
      fullPath: '/service-management'
      preLoaderRoute: typeof AuthenticatedServiceManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/observability/': {
      id: '/_authenticated/observability/'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof AuthenticatedObservabilityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mcp-management/': {
      id: '/_authenticated/mcp-management/'
      path: '/mcp-management'
      fullPath: '/mcp-management'
      preLoaderRoute: typeof AuthenticatedMcpManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/external-calls/': {
      id: '/_authenticated/external-calls/'
      path: '/external-calls'
      fullPath: '/external-calls'
      preLoaderRoute: typeof AuthenticatedExternalCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cluster-chat/': {
      id: '/_authenticated/cluster-chat/'
      path: '/cluster-chat'
      fullPath: '/cluster-chat'
      preLoaderRoute: typeof AuthenticatedClusterChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alert-management/': {
      id: '/_authenticated/alert-management/'
      path: '/alert-management'
      fullPath: '/alert-management'
      preLoaderRoute: typeof AuthenticatedAlertManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat/': {
      id: '/_authenticated/ai-chat/'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-management/': {
      id: '/_authenticated/agent-management/'
      path: '/agent-management'
      fullPath: '/agent-management'
      preLoaderRoute: typeof AuthenticatedAgentManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/auth': {
      id: '/_authenticated/debug/auth'
      path: '/debug/auth'
      fullPath: '/debug/auth'
      preLoaderRoute: typeof AuthenticatedDebugAuthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles/': {
      id: '/_authenticated/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/permissions/': {
      id: '/_authenticated/settings/permissions/'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/menus/': {
      id: '/_authenticated/settings/menus/'
      path: '/menus'
      fullPath: '/settings/menus'
      preLoaderRoute: typeof AuthenticatedSettingsMenusIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/logs/operation/': {
      id: '/_authenticated/logs/operation/'
      path: '/logs/operation'
      fullPath: '/logs/operation'
      preLoaderRoute: typeof AuthenticatedLogsOperationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/chat/': {
      id: '/_authenticated/logs/chat/'
      path: '/logs/chat'
      fullPath: '/logs/chat'
      preLoaderRoute: typeof AuthenticatedLogsChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsMenusIndexRoute: typeof AuthenticatedSettingsMenusIndexRoute
  AuthenticatedSettingsPermissionsIndexRoute: typeof AuthenticatedSettingsPermissionsIndexRoute
  AuthenticatedSettingsRolesIndexRoute: typeof AuthenticatedSettingsRolesIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsMenusIndexRoute: AuthenticatedSettingsMenusIndexRoute,
    AuthenticatedSettingsPermissionsIndexRoute:
      AuthenticatedSettingsPermissionsIndexRoute,
    AuthenticatedSettingsRolesIndexRoute: AuthenticatedSettingsRolesIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDebugAuthRoute: typeof AuthenticatedDebugAuthRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAgentManagementIndexRoute: typeof AuthenticatedAgentManagementIndexRoute
  AuthenticatedAiChatIndexRoute: typeof AuthenticatedAiChatIndexRoute
  AuthenticatedAlertManagementIndexRoute: typeof AuthenticatedAlertManagementIndexRoute
  AuthenticatedClusterChatIndexRoute: typeof AuthenticatedClusterChatIndexRoute
  AuthenticatedExternalCallsIndexRoute: typeof AuthenticatedExternalCallsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMcpManagementIndexRoute: typeof AuthenticatedMcpManagementIndexRoute
  AuthenticatedObservabilityIndexRoute: typeof AuthenticatedObservabilityIndexRoute
  AuthenticatedServiceManagementIndexRoute: typeof AuthenticatedServiceManagementIndexRoute
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedLogsChatIndexRoute: typeof AuthenticatedLogsChatIndexRoute
  AuthenticatedLogsOperationIndexRoute: typeof AuthenticatedLogsOperationIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDebugAuthRoute: AuthenticatedDebugAuthRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAgentManagementIndexRoute:
    AuthenticatedAgentManagementIndexRoute,
  AuthenticatedAiChatIndexRoute: AuthenticatedAiChatIndexRoute,
  AuthenticatedAlertManagementIndexRoute:
    AuthenticatedAlertManagementIndexRoute,
  AuthenticatedClusterChatIndexRoute: AuthenticatedClusterChatIndexRoute,
  AuthenticatedExternalCallsIndexRoute: AuthenticatedExternalCallsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMcpManagementIndexRoute: AuthenticatedMcpManagementIndexRoute,
  AuthenticatedObservabilityIndexRoute: AuthenticatedObservabilityIndexRoute,
  AuthenticatedServiceManagementIndexRoute:
    AuthenticatedServiceManagementIndexRoute,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedLogsChatIndexRoute: AuthenticatedLogsChatIndexRoute,
  AuthenticatedLogsOperationIndexRoute: AuthenticatedLogsOperationIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
